# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME

# Dark Glassy Elegante
background #19191C
foreground #CDD6F4
selection_foreground #19191C
selection_background #89B4FA
cursor #CDD6F4
cursor_text_color #19191C
url_color #89B4FA
active_border_color #89B4FA
inactive_border_color #6C7086
bell_border_color #F38E7D
active_tab_foreground #19191C
active_tab_background #89B4FA
inactive_tab_foreground #CDD6F4
inactive_tab_background #1E1E2E
tab_bar_background #1E1E2E

# Paleta de cores (0-15)
# -- DARK --
color0  #313244
color1  #F38E8D
color2  #A6E3A1
color3  #F9E2AF
color4  #89B4FA
color5  #F39C7D
color6  #94E2D5
color7  #BAC2DE

# -- BRIGTH --
color8  #585B70
color9  #F38E8D
color10 #A6E3A1
color11 #F9E2AF
color12 #89B4FA
color13 #F3BA8D
color14 #94E2D5
color15 #CDD6F4

#: Fonts
font_family JetBrainsMono Nerd Font Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 12.25

# Tengwar (U+E000 - U+E07F)
# symbol_map U+E000-U+E07F FreeMonoTengwar
# Cirth (U+E080 - U+E0FF)
# symbol_map U+E080-U+E0FF Fairfax HD

#: Aparência Visual
background_opacity 0.95
dynamic_background_opacity yes
background_blur 10
macos_colorspace displayp3

#: Cursor customization
cursor_shape beam
cursor_blink_interval 0.5

#: Scrollback
scrollback_lines 9000

#: Mouse
url_style curly
open_url_with default
detect_urls yes

#: Window layout
remember_window_size yes
initial_window_width 640
initial_window_height 400
window_border_width 0.5pt
window_padding_width 4

#: Tab bar
tab_bar_edge bottom
tab_bar_style fade
tab_bar_min_tabs 2

#: Advanced
shell .
editor .
allow_remote_control no

#: OS specific tweaks
# Para Linux com Wayland
wayland_titlebar_color system

# Para macOS
macos_titlebar_color system
macos_option_as_alt yes
macos_quit_when_last_window_closed no
map alt+q send_text all \x2f
map alt+w send_text all \x3f

#: Keyboard shortcuts
kitty_mod ctrl+shift

# Clipboard
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard

# Scrolling
map kitty_mod+up scroll_line_up
map kitty_mod+down scroll_line_down
map kitty_mod+page_up scroll_page_up
map kitty_mod+page_down scroll_page_down
map kitty_mod+home scroll_home
map kitty_mod+end scroll_end

# Window management
map kitty_mod+enter new_window
map kitty_mod+w close_window
map kitty_mod+] next_window
map kitty_mod+[ previous_window

# Tab management
map kitty_mod+t new_tab_with_cwd
map kitty_mod+q close_tab
map kitty_mod+right next_tab
map kitty_mod+left previous_tab

# Font sizes
map kitty_mod+equal change_font_size all +2.0
map kitty_mod+minus change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0

# Miscellaneous
map kitty_mod+f5 load_config_file
map kitty_mod+f11 toggle_fullscreen
